# Generated by Django 5.0.6 on 2024-06-30 09:56

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə edilmə tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nəşr tarixi')),
                ('blog_title', models.CharField(max_length=150, unique=True, verbose_name='Blogun başlığı')),
                ('blog_content', ckeditor.fields.RichTextField(null=True, verbose_name='Blogun mətni')),
                ('blog_image', models.ImageField(unique=True, upload_to='blog/', verbose_name='Blogun fotosu')),
                ('slug', models.SlugField(blank=True, help_text='Bu qismi boş buraxın. Avtomatik doldurulacaq.', max_length=250, null=True, verbose_name='Link adı')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Blog_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə edilmə tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nəşr tarixi')),
                ('comment_text', models.TextField(verbose_name='Bloga rəylər')),
                ('slug', models.SlugField(blank=True, help_text='Bu qismi boş buraxın. Avtomatik doldurulacaq.', max_length=250, null=True, verbose_name='Link adı')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bloga rəy',
                'verbose_name_plural': 'Bloga rəylər',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kateqoriya adı')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Link adı')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='IPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_ip', models.GenericIPAddressField(editable=False, null=True, verbose_name='IP ünvanı')),
            ],
            options={
                'verbose_name': 'IP ünvanı',
                'verbose_name_plural': 'IP ünvanları',
            },
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Teq adı')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Link adı')),
            ],
            options={
                'verbose_name': 'Teq',
                'verbose_name_plural': 'Teqlər',
            },
        ),
    ]
